Fix HistoricForeignKey when used together with prefetch_related()
jazzband/django-simple-history pull request #1159
Opened 2023-04-14 11:54 UTC by mr-mare

## Description
This fixes behaviour of `HistoricForeignKey` when used together with `prefetch_related()`.

The following is sufficient to reproduce the bug:
- models:
```python
from django.db import models
from simple_history.models import HistoricalRecords, HistoricForeignKey

class Poll(models.Model):
    question = models.CharField(max_length=200)

    history = HistoricalRecords()

class Choice(models.Model):
    poll = HistoricForeignKey(Poll, on_delete=models.CASCADE)
    choice = models.CharField(max_length=200)
    votes = models.IntegerField()

    history = HistoricalRecords()
```
- code:
```python
from poll.models import Poll, Choice

why_poll = Poll.objects.create(question="why?")
how_poll = Poll.objects.create(question="how?")

Choice.objects.create(poll=why_poll, votes=0)
Choice.objects.create(poll=how_poll, votes=0)

for poll in Poll.objects.prefetch_related("choice_set").all():
    print(poll.choice_set.all())

# expected result:
# <QuerySet [<Choice: Choice object (1)>]>
# <QuerySet [<Choice: Choice object (2)>]>

# actual result:
# <QuerySet [<Choice: Choice object (1)>]>
# <QuerySet []>
```

## Related Issue
#1152 

## Motivation and Context
Property `related_manager_cls` is defined in [`HistoricReverseManyToOneDescriptor`](../blob/3.3.0/simple_history/models.py#L827). This property returns a function call of [`create_reverse_many_to_one_manager`](https://github.com/django/django/blob/4.2/django/db/models/fields/related_descriptors.py#L632) function and passes it `HistoricRelationModelManager` as an argument. However, `create_reverse_many_to_one_manager` defines `RelatedManager`, which subclasses the manager passed as an argument and returns this `RelatedManager` class.

When `prefetch_related` is used, [`get_prefetch_queryset`](https://github.com/django/django/blob/4.2/django/db/models/fields/related_descriptors.py#L730) method of `RelatedManager` is called.
The problem lies in the fact that it bypasses `RelatedManager.get_queryset` method which does filtering to instance (`_apply_rel_filters`) by calling `super().get_queryset()`. But due to inheritance, it gets evaluated to `HistoricRelationModelManager.get_queryset` which does the same filtering as well.

This SQL is generated then (notice the `"poll_choice"."poll_id" = 1` condition):
```sql
SELECT "poll_poll"."id", "poll_poll"."question" FROM "poll_poll"
SELECT "poll_choice"."id", "poll_choice"."poll_id", "poll_choice"."choice", "poll_choice"."votes" FROM "poll_choice" WHERE ("poll_choice"."poll_id" = 1 AND "poll_choice"."poll_id" IN (1, 2))
```

Removing `_apply_rel_filters` call from `HistoricRelationModelManager.get_queryset` solves this problem.

On the other hand, since `create_reverse_many_to_one_manager` returns `RelatedManager`, rather than `HistoricRelationModelManager`, the only way to access `HistoricRelationModelManager.get_queryset` is by calling `super().get_queryset()` from `RelatedManager`. This call can be found:
- in `RelatedManager.get_prefetch_queryset` where it is undesired,
- in `RelatedManager.get_queryset` where `_apply_rel_filters` is called right after `super().get_queryset()`.

Therefore, I believe it is safe to remove it.

## How Has This Been Tested?
Added new tests.

## Screenshots (if appropriate):

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] I have run the `pre-commit run` command to format and lint.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [ ] I have added my name and/or github handle to `AUTHORS.rst`
- [x] I have added my change to `CHANGES.rst`
- [x] All new and existing tests passed.

2023-11-02 14:57 UTC, evanhaldane commented
Plans to review/merge this?

(I'm in the process of integrating this package for the first time and I spent a few hours chasing around a bug until I realized it was caused by this issue.)

cc: @ddabble ?

2024-06-21 01:58 UTC, anyidea commented
any progress?

2024-09-05 14:26 UTC, robertofd-nextmatter commented
Any reason why this is not getting merged? We are also having the same issue

2024-09-05 15:24 UTC, mr-mare commented
I'm happy to help. If there is anything I can do, please let me know.

2024-09-08 20:13 UTC, ddabble requested changes
Nice, good job investigating this solution! 😄 I agree with your reasoning for why it should be safe removing the call to `_apply_rel_filters()`. Furthermore, it looks like `create_reverse_many_to_one_manager()` usually gets a standard `Manager` as its `superclass` arg, which doesn't contain any `_apply_rel_filters()` method. And so it seems likely that `RelatedManager` was designed to be expecting that its superclass' `get_queryset()` method doesn't do any of the things that `_apply_rel_filters()` does, which again supports the decision to remove the call.

Do you think we should remove the `try` block with `self.instance._prefetched_objects_cache[...]` as well? The exact same call is in `RelatedManager.get_queryset()`, but it doesn't seem to hurt performance much... Though I'm not sure about the consequences of removing it (or any unknown, existing bugs that might live on if we leave it there, for that matter), considering that `RelatedManager.get_prefetch_querysets()` seems to skip that cache lookup by calling `super().get_queryset()`, combined with the fact that the mentioned standard `Manager` also doesn't make any cache lookups in `get_queryset()` 🤔

Lastly, could you add a test case for a nested `prefetch_related()` call, like the `SubSub` examples in the description of #1152? 🙂 I guess it should be enough e.g. adding a new history-tracked model with a `HistoricForeignKey` referencing `TestHistoricParticipanToHistoricOrganization`, and test with the different arguments to `prefetch_related()` from the mentioned `SubSub` examples, which would include `"historic_participants__<subsub related_name>"` and various nested variants using `Prefetch(...)`.

Other than that, very clear and thorough test cases! And sorry that it took so long getting to reviewing this!

2026-04-29 11:29 UTC, tomhampshire commented
Hi @mr-mare, hope you don't mind: I've opened #1604, which is your commit cherry-picked onto current master (your authorship preserved) plus two follow-up commits addressing @ddabble's review (the cache-lookup removal, and a nested prefetch regression test for the SubSub case from #1152). Closing-or-keeping this PR is up to you and the maintainers; please feel free to take ownership of #1604 or reuse anything from it as you see fit.

2026-07-16 22:55 UTC, ddabble commented
Superseded by #1604

2026-07-16 22:55 UTC, closed without merging