add id translation
jazzband/django-simple-history pull request #1198
Opened 2023-06-30 09:28 UTC by kiraware

## Description
Support Bahasa Indonesia translation

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have run the `pre-commit run` command to format and lint.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] I have added my name and/or github handle to `AUTHORS.rst`
- [x] I have added my change to `CHANGES.rst`
- [ ] All new and existing tests passed.

2023-07-01 15:54 UTC, ddabble requested changes
Looks good to me :) Just a couple minor requests:

2023-07-01 15:54 UTC, ddabble commented on simple_history/locale/id/LC_MESSAGES/django.po
> +#, fuzzy
Please remove this line 🙂 
```suggestion
```

2023-07-01 15:54 UTC, ddabble commented on simple_history/locale/id/LC_MESSAGES/django.po
> +#: .\simple_history\admin.py:102
...and add an empty line here:
```suggestion
"Plural-Forms: nplurals=1; plural=0;\n"

#: .\simple_history\admin.py:102
```

2023-07-02 08:16 UTC, kiraware commented
Done @ddabble. Thanks for your response.

2023-07-02 12:30 UTC, ddabble approved these changes
Thank you! 😊

2023-07-02 12:30 UTC, merged

2023-07-03 02:51 UTC, kiraware commented
Your welcome :)