Batch with additional historical model fields
jazzband/django-simple-history pull request #1248
Opened 2023-09-08 02:24 UTC by NoelJames

## Description
Adds ability to update history model attributes (custom ones) during a batch job.

## Related Issue
closes #1247

## Motivation and Context
Adding [additional fields to historical models](https://django-simple-history.readthedocs.io/en/latest/historical_model.html#adding-additional-fields-to-historical-models) has been a useful approach to capturing some necessary data for me. However, I also have some operations that require bulk_update_with_history and bulk_create_with_history but these functions do not support these customized field value.

## How Has This Been Tested?
The pr includes tests

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have run the `pre-commit run` command to format and lint.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] I have added my name and/or github handle to `AUTHORS.rst`
- [x] I have added my change to `CHANGES.rst`
- [x] All new and existing tests passed.

2023-09-08 14:16 UTC, NoelJames commented
I wanted to note a few things about this 

I can not get the documents to generate on my machine  or run the `pre-commit run`.  For the docuemts i get a cryptic error that says `docs: FAIL code 2` and  i can not find the `pre-commit` command. The tests do run. 

Maybe `**kwargs` is not the best. I could change to param named `custom` or `additional` and expect a dict that would almost be the same thing?

I did not add the pydoc to the function which had the signatures changed

let me know if this looks like something you'd go forward with and I'll make changes

2023-09-14 17:02 UTC, ddabble commented
> For the docuemts i get a cryptic error that says `docs: FAIL code 2`

I wouldn't worry about this, as the docs are built through the CI anyway 🙂 (See the checks at the bottom of this page - which contain this link to the build for this PR: https://django-simple-history--1248.org.readthedocs.build/en/1248/.)

> i can not find the `pre-commit` command.

This sounds like `pre-commit` is not installed on your machine 🤔 See [`pre-commit`'s website](https://pre-commit.com/#installation) if that's the case. Otherwise, the command is also run through the CI, so you don't *have* to run it locally :)

> Maybe `**kwargs` is not the best. I could change to param named `custom` or `additional` and expect a dict that would almost be the same thing?

Yeah, I agree. The `custom_` prefixes of the passed kwargs are pretty unconventional, and so it has potential for causing confusion. I think it would indeed be better to replace the `**kwargs` like you mentioned, but preferably name the parameter something a little more explicit, like `extra_historical_attrs`/`custom_historical_attrs`.

> I did not add the pydoc to the function which had the signatures changed

It would be great if you could update the docstrings of `bulk_create_with_history()` and `bulk_update_with_history()` 🙂

> let me know if this looks like something you'd go forward with and I'll make changes

Sure, this absolutely seems useful! Thank you for taking the time 😊

2023-09-14 17:03 UTC, ddabble requested changes
Some additional changes to the ones discussed above:

2023-09-25 16:10 UTC, NoelJames commented
I've submitted the suggested changes.

2023-09-25 17:57 UTC, NoelJames commented
the failing tests on `Django main` with `AttributeError: 'BulkHistoryUpdateTestCase' object has no attribute 'assertQuerysetEqual'. Did you mean: 'assertQuerySetEqual'?` are not mine

2023-09-25 19:25 UTC, ddabble requested changes
Nice! Some feedback on the new code:

2023-09-25 19:25 UTC, ddabble commented on simple_history/manager.py
> +
This is a little bit shorter:
```suggestion
                **(custom_historical_attrs or {}),
            )
```

2023-09-25 19:25 UTC, ddabble commented on docs/common_issues.rst
> +    >>> data[0].history.get().session
The objects in `data` likely already have history records, so we should ideally use `latest()` in this example to not induce a `MultipleObjectsReturned` error (this is, of course, in contrast to using `bulk_create_with_history()` above).
```suggestion
    >>> data[0].history.latest().session
```

2023-09-25 19:25 UTC, ddabble commented on docs/common_issues.rst
> +        PollWithHistoricalSessionAttr(id=x, question='Question ' + str(x))
```suggestion
        PollWithHistoricalSessionAttr(id=x, question=f'Question {x}')
```

2023-09-25 19:25 UTC, ddabble commented on docs/common_issues.rst
> +A field ``session`` would be passed as ``custom_historical_attrs={'session': '127.0.0.1'}``.
Improvement suggestion:
```suggestion
If you're using `additional fields in historical models`_ and have custom fields to
batch-create into the history, pass the optional dict argument ``custom_historical_attrs``
containing the field names and values.
A field ``session`` would be passed as ``custom_historical_attrs={'session': 'training'}``.
```

2023-09-25 19:25 UTC, ddabble commented on docs/common_issues.rst
> +`custom_historical_attrs={'ip_address': '127.0.0.1'}`.
Improvement suggestion:
```suggestion
If you're using `additional fields in historical models`_ and have custom fields to
batch-update into the history, pass the optional dict argument ``custom_historical_attrs``
containing the field names and values.
A field ``session`` would be passed as ``custom_historical_attrs={'session': 'jam'}``.
```

2023-09-25 19:30 UTC, ddabble commented
>  the failing tests on `Django main` with `AttributeError: 'BulkHistoryUpdateTestCase' object has no attribute 'assertQuerysetEqual'. Did you mean: 'assertQuerySetEqual'?` are not mine

Yeah, it's caused by some recent changes in Django's `main` branch, like you mentioned. The tests were fixed in #1258, so if you want, you can rebase on `master`, but I'll merge in any case :)

2023-09-25 19:45 UTC, NoelJames commented on simple_history/tests/tests/test_utils.py
> +            update_data,
it is out of scope :monocle_face:

2023-09-25 19:51 UTC, NoelJames commented
Alright, I'll update master branch fix the doc string and then I'll take the PR out of draft when its ready.

Thanks for your help

2023-09-25 20:05 UTC, NoelJames commented on simple_history/utils.py
> +    custom_historical_attrs=None,
added https://github.com/jazzband/django-simple-history/pull/1248/commits/8f8a0b4995fe9a8261d010bf6776f26fe5f45d6c

2023-09-25 20:05 UTC, NoelJames commented on simple_history/utils.py
> +    custom_historical_attrs=None,
added https://github.com/jazzband/django-simple-history/pull/1248/commits/8f8a0b4995fe9a8261d010bf6776f26fe5f45d6c

2023-09-25 21:52 UTC, ddabble commented
I noticed that the `bulk_update_with_history()` example was missing a value for the `fields` argument, and that the test case for the same function was providing a field name that was logically unnecessary - as no fields were actually updated on the model - so I pushed commit 42c59aaf09e97355f59d22961766d30b12594906 :)

2023-09-25 22:02 UTC, ddabble approved these changes
Great job, thank you! 😊

2023-09-25 22:02 UTC, ddabble commented
@NoelJames Lastly, before merging, would you like to rebase to clean up your commits? 🙂 Otherwise, I'll just squash them, as to me they seem to be telling one coherent story (except for 42c59aaf09e97355f59d22961766d30b12594906, I guess).

2023-09-25 22:09 UTC, NoelJames commented
I got pretty messy there. And rebase has not been very good to me so, please squash away.

2023-09-25 22:19 UTC, ddabble commented
No worries, it's just natural when working on a PR after feedback :) But alright 👌

2023-09-25 22:45 UTC, merged