Diff improvements (performance + `included_fields`)
jazzband/django-simple-history pull request #776
Opened 2021-01-06 17:06 UTC by RealOrangeOne

## Description

Reduce the number of queries needed when calling `diff_against` (down to 0). 

Also implement `included_fields`, so only certain fields will be compared. In this new implementation of diffing, old fields won't be compared at all, and can be deferred from querying if needed.

## Related Issue

`included_fields` was mentioned in https://github.com/jazzband/django-simple-history/pull/576#issuecomment-584761832, and as I was here, I added. Can extract into a separate PR if needed.

## Motivation and Context

`model_to_dict` will do queries for M2M fields against real tables. As these are always the same, it never impacts history. Removing this reduces the number of queries massively.

Additionally, diffing involved getting real instances of the model using `.instance`, which was unnecessary. The diffing can be using the history instances directly, saving a lot of computation. The fields list is pulled off the real model which means `history_*`fields are still excluded correctly.

## How Has This Been Tested?

- [x] Tests have been added to cover changes
- [ ] Has been run against live project unittests successfully

## Screenshots (if appropriate):

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have run the `make format` command to format my code
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [ ] I have added my name and/or github handle to `AUTHORS.rst`
- [ ] I have added my change to `CHANGES.rst`
- [x] All new and existing tests passed.

2021-02-04 16:02 UTC, RealOrangeOne commented
Turns out the current code also causes additional queries for excluded fields, which isn't good. Would be great to get this merged and released soon, as the performance improvements are vast!

2021-09-14 14:04 UTC, sebashwa commented
Hey, I created a similar change and then just saw this one.
+1 for integrating ASAP

What do you think about always excluding m2m-fields as they are not supported anyways @RealOrangeOne:

e.g.
```python
def diff_against(self, old_history, excluded_fields=None)
    ---snip---
    for model_field in self.instance._meta.get_fields():
        if model_field.many_to_many:
            excluded_fields.append(model_field.name)
    ---snip---
```

2021-09-14 14:14 UTC, sebashwa submitted a review, later dismissed

2021-09-16 02:49 UTC, jeking3 commented
If you could rebase on master and make sure all the new branches are covered by tests, will re-review.

2021-09-20 16:39 UTC, jeking3 requested changes
I would leave the KeyError handling in place for invalid fields and add this test to the HistoricalRecordsTest:

```
+        with self.assertRaises(KeyError):
+            delta = new_record.diff_against(old_record, included_fields=["this_field_does_not_exist"])
```
Also rebase on current master, then if we get a clean run we'll be all set.

2021-09-22 12:11 UTC, jeking3 approved these changes

2021-09-22 12:11 UTC, merged